### ISSUE TITLE
Bending display exception

### ISSUE THREAD

**Issue by Nokorbis** [Avatar-Realms/spigot-bending#124]
[17:06:08] [Server thread/INFO]: Noko issued server command: /b display Volph
[17:06:08] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'b' in plugin Bending v6.1.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:908) ~[?:1.8.0_101]
at java.lang.StringBuilder.substring(StringBuilder.java:76) ~[?:1.8.0_101]
at net.bendercraft.spigot.bending.commands.subcommands.DisplayExecution.execute(DisplayExecution.java:59) ~[?:?]
at net.bendercraft.spigot.bending.commands.BendingCommandExecutor.onCommand(BendingCommandExecutor.java:76) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.2.jar:git-Spigot-455072c-43ab266]
... 15 more

**Comment by Koudja** [comment]
Déjà corrigé : 240191728d23252441bceab9086f62fbfd4ff361 mais personne n'a poussé le changement sur le serveur.
