### ISSUE TITLE
Could not pass BendingDamageEvent to Sentry

### ISSUE THREAD

**Issue by Nokorbis** [Avatar-Realms/spigot-bending#74]
[16:29:38] [Server thread/ERROR]: Could not pass event BendingDamageEvent to Sentry v1.9.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.avatar.realms.spigot.bending.Bending.callEvent(Bending.java:127) [spigot-bending.jar:?]
    at net.avatar.realms.spigot.bending.utils.DamageTools.damageEntity(DamageTools.java:54) [spigot-bending.jar:?]
    at net.avatar.realms.spigot.bending.utils.EntityTools.damageEntity(EntityTools.java:349) [spigot-bending.jar:?]
    at net.avatar.realms.spigot.bending.abilities.air.AirSwipe.advanceSwipe(AirSwipe.java:298) [spigot-bending.jar:?]
    at net.avatar.realms.spigot.bending.abilities.air.AirSwipe.progress(AirSwipe.java:195) [spigot-bending.jar:?]
    at net.avatar.realms.spigot.bending.abilities.BendingAbility.tick(BendingAbility.java:109) [spigot-bending.jar:?]
    at net.avatar.realms.spigot.bending.abilities.AbilityManager.progressAllAbilities(AbilityManager.java:110) [spigot-bending.jar:?]
    at net.avatar.realms.spigot.bending.controller.BendingManager.run(BendingManager.java:49) [spigot-bending.jar:?]
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NullPointerException
    at net.aufdemrand.sentry.SentryInstance.die(SentryInstance.java:525) ~[?:?]
    at net.aufdemrand.sentry.SentryInstance.onDamage(SentryInstance.java:1238) ~[?:?]
    at net.aufdemrand.sentry.SentryListener.onDamage(SentryListener.java:270) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor261.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-104c8c8-00d3334]
    ... 18 more

**Comment by Koudja** [comment]
Je ne pense pas que le problème vient du bending, mais plutôt de sentry (avec un simple DamageEvent).
