### ISSUE TITLE
Could not pass event PlayerVelocityEvent to Bending v6.1.0

### ISSUE THREAD

**Issue by Super-Thomate** [Avatar-Realms/spigot-bending#78]
C'est apparu très souvent, je ne sais pas du tout ce que c'est...
[12:10:26] [Server thread/ERROR]: Could not pass event PlayerVelocityEvent to Bending v6.1.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-7a6b143]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.2.jar:git-Spigot-e6f93f4-7a6b143]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-7a6b143]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-7a6b143]
    at net.minecraft.server.v1_9_R1.EntityTrackerEntry.track(EntityTrackerEntry.java:243) [spigot-1.9.2.jar:git-Spigot-e6f93f4-7a6b143]
    at net.minecraft.server.v1_9_R1.EntityTracker.updatePlayers(EntityTracker.java:179) [spigot-1.9.2.jar:git-Spigot-e6f93f4-7a6b143]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:809) [spigot-1.9.2.jar:git-Spigot-e6f93f4-7a6b143]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-7a6b143]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-7a6b143]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-7a6b143]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NullPointerException

**Comment by Koudja** [comment]
Probablement résolu avec 8370608
